### ISSUE TITLE
Features Planning to Add & Problems

### ISSUE THREAD

**Issue by WangNianyi2001** [SonnAdolf/sonne_blog#1]
Plannings: 
- Comment
- Category
- View Count
- Auto Login

Problems: 
- Messy Codes

**Comment by hinatatatakae** [comment]
Thanks for your advice, I'll try to do these things in version 2.

**Comment by WangNianyi2001** [comment]
Add an un-register button please!

**Comment by hinatatatakae** [comment]
日向博客目前用户就几个。实际上基本只有我。在这种情况下，不觉得注销按钮有任何实际意义。
